/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BlogCategory = { 'art' : null } |
  { 'letters' : null } |
  { 'lyrics' : null } |
  { 'poems' : null } |
  { 'prose' : null } |
  { 'quotes' : null } |
  { 'essays' : null } |
  { 'photographs' : null };
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'authorNote' : [] | [string],
  'publishedAt' : Time,
  'imageUrl' : [] | [ExternalBlob],
  'category' : BlogCategory,
}
export interface Cause {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : [] | [ExternalBlob],
  'externalUrl' : string,
  'causeCategory' : CauseCategory,
}
export type CauseCategory = { 'earth' : null } |
  { 'mental_health' : null } |
  { 'humanity' : null };
export type ExternalBlob = Uint8Array;
export interface Feature {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : [] | [ExternalBlob],
  'externalUrl' : string,
}
export type FulfillmentType = { 'external_pod' : null } |
  { 'digital_download' : null };
export interface Product {
  'id' : bigint,
  'title' : string,
  'shopCategory' : ShopCategory,
  'createdAt' : Time,
  'description' : string,
  'imageUrl' : ExternalBlob,
  'fulfillmentType' : FulfillmentType,
  'externalUrl' : string,
  'price' : string,
}
export interface Publication {
  'id' : bigint,
  'title' : string,
  'year' : string,
  'description' : string,
  'coverImage' : [] | [ExternalBlob],
  'publicationType' : PublicationType,
  'externalUrl' : string,
}
export type PublicationType = { 'solo' : null } |
  { 'collaboration' : null } |
  { 'anthologies' : null };
export type ShopCategory = { 'art' : null } |
  { 'creativity' : null } |
  { 'words' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoicePost {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'createdAt' : Time,
  'parentId' : [] | [bigint],
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<
    [string, BlogCategory, string, [] | [ExternalBlob], [] | [string]],
    bigint
  >,
  'createCause' : ActorMethod<
    [string, CauseCategory, string, [] | [ExternalBlob], string],
    bigint
  >,
  'createFeature' : ActorMethod<
    [string, string, [] | [ExternalBlob], string],
    bigint
  >,
  'createProduct' : ActorMethod<
    [
      string,
      ShopCategory,
      string,
      ExternalBlob,
      string,
      string,
      FulfillmentType,
    ],
    bigint
  >,
  'createPublication' : ActorMethod<
    [string, PublicationType, string, [] | [ExternalBlob], string, string],
    bigint
  >,
  'createVoicePost' : ActorMethod<[string, string, [] | [bigint]], bigint>,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteCause' : ActorMethod<[bigint], undefined>,
  'deleteFeature' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deletePublication' : ActorMethod<[bigint], undefined>,
  'deleteVoicePost' : ActorMethod<[bigint], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllCauses' : ActorMethod<[], Array<Cause>>,
  'getAllFeatures' : ActorMethod<[], Array<Feature>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllPublications' : ActorMethod<[], Array<Publication>>,
  'getAllVoicePosts' : ActorMethod<[], Array<VoicePost>>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogPostsByCategory' : ActorMethod<[BlogCategory], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCause' : ActorMethod<[bigint], [] | [Cause]>,
  'getCausesByCategory' : ActorMethod<[CauseCategory], Array<Cause>>,
  'getChildVoicePosts' : ActorMethod<[bigint], Array<VoicePost>>,
  'getFeature' : ActorMethod<[bigint], [] | [Feature]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[ShopCategory], Array<Product>>,
  'getPublication' : ActorMethod<[bigint], [] | [Publication]>,
  'getPublicationsByType' : ActorMethod<[PublicationType], Array<Publication>>,
  'getRootVoicePosts' : ActorMethod<[], Array<VoicePost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVoicePost' : ActorMethod<[bigint], [] | [VoicePost]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, BlogCategory, string, [] | [ExternalBlob], [] | [string]],
    undefined
  >,
  'updateCause' : ActorMethod<
    [bigint, string, CauseCategory, string, [] | [ExternalBlob], string],
    undefined
  >,
  'updateFeature' : ActorMethod<
    [bigint, string, string, [] | [ExternalBlob], string],
    undefined
  >,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      ShopCategory,
      string,
      ExternalBlob,
      string,
      string,
      FulfillmentType,
    ],
    undefined
  >,
  'updatePublication' : ActorMethod<
    [
      bigint,
      string,
      PublicationType,
      string,
      [] | [ExternalBlob],
      string,
      string,
    ],
    undefined
  >,
  'updateVoicePost' : ActorMethod<
    [bigint, string, string, [] | [bigint]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];