/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogCategory = IDL.Variant({
  'art' : IDL.Null,
  'letters' : IDL.Null,
  'lyrics' : IDL.Null,
  'poems' : IDL.Null,
  'prose' : IDL.Null,
  'quotes' : IDL.Null,
  'essays' : IDL.Null,
  'photographs' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CauseCategory = IDL.Variant({
  'earth' : IDL.Null,
  'mental_health' : IDL.Null,
  'humanity' : IDL.Null,
});
export const ShopCategory = IDL.Variant({
  'art' : IDL.Null,
  'creativity' : IDL.Null,
  'words' : IDL.Null,
});
export const FulfillmentType = IDL.Variant({
  'external_pod' : IDL.Null,
  'digital_download' : IDL.Null,
});
export const PublicationType = IDL.Variant({
  'solo' : IDL.Null,
  'collaboration' : IDL.Null,
  'anthologies' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'authorNote' : IDL.Opt(IDL.Text),
  'publishedAt' : Time,
  'imageUrl' : IDL.Opt(ExternalBlob),
  'category' : BlogCategory,
});
export const Cause = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(ExternalBlob),
  'externalUrl' : IDL.Text,
  'causeCategory' : CauseCategory,
});
export const Feature = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Opt(ExternalBlob),
  'externalUrl' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'shopCategory' : ShopCategory,
  'createdAt' : Time,
  'description' : IDL.Text,
  'imageUrl' : ExternalBlob,
  'fulfillmentType' : FulfillmentType,
  'externalUrl' : IDL.Text,
  'price' : IDL.Text,
});
export const Publication = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'year' : IDL.Text,
  'description' : IDL.Text,
  'coverImage' : IDL.Opt(ExternalBlob),
  'publicationType' : PublicationType,
  'externalUrl' : IDL.Text,
});
export const VoicePost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Time,
  'parentId' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [
        IDL.Text,
        BlogCategory,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createCause' : IDL.Func(
      [IDL.Text, CauseCategory, IDL.Text, IDL.Opt(ExternalBlob), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createFeature' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        ShopCategory,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        IDL.Text,
        FulfillmentType,
      ],
      [IDL.Nat],
      [],
    ),
  'createPublication' : IDL.Func(
      [
        IDL.Text,
        PublicationType,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createVoicePost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'deleteCause' : IDL.Func([IDL.Nat], [], []),
  'deleteFeature' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deletePublication' : IDL.Func([IDL.Nat], [], []),
  'deleteVoicePost' : IDL.Func([IDL.Nat], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllCauses' : IDL.Func([], [IDL.Vec(Cause)], ['query']),
  'getAllFeatures' : IDL.Func([], [IDL.Vec(Feature)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
  'getAllVoicePosts' : IDL.Func([], [IDL.Vec(VoicePost)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostsByCategory' : IDL.Func(
      [BlogCategory],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCause' : IDL.Func([IDL.Nat], [IDL.Opt(Cause)], ['query']),
  'getCausesByCategory' : IDL.Func(
      [CauseCategory],
      [IDL.Vec(Cause)],
      ['query'],
    ),
  'getChildVoicePosts' : IDL.Func([IDL.Nat], [IDL.Vec(VoicePost)], ['query']),
  'getFeature' : IDL.Func([IDL.Nat], [IDL.Opt(Feature)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ShopCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getPublication' : IDL.Func([IDL.Nat], [IDL.Opt(Publication)], ['query']),
  'getPublicationsByType' : IDL.Func(
      [PublicationType],
      [IDL.Vec(Publication)],
      ['query'],
    ),
  'getRootVoicePosts' : IDL.Func([], [IDL.Vec(VoicePost)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVoicePost' : IDL.Func([IDL.Nat], [IDL.Opt(VoicePost)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBlogPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        BlogCategory,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateCause' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        CauseCategory,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateFeature' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Text],
      [],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        ShopCategory,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        IDL.Text,
        FulfillmentType,
      ],
      [],
      [],
    ),
  'updatePublication' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        PublicationType,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateVoicePost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogCategory = IDL.Variant({
    'art' : IDL.Null,
    'letters' : IDL.Null,
    'lyrics' : IDL.Null,
    'poems' : IDL.Null,
    'prose' : IDL.Null,
    'quotes' : IDL.Null,
    'essays' : IDL.Null,
    'photographs' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CauseCategory = IDL.Variant({
    'earth' : IDL.Null,
    'mental_health' : IDL.Null,
    'humanity' : IDL.Null,
  });
  const ShopCategory = IDL.Variant({
    'art' : IDL.Null,
    'creativity' : IDL.Null,
    'words' : IDL.Null,
  });
  const FulfillmentType = IDL.Variant({
    'external_pod' : IDL.Null,
    'digital_download' : IDL.Null,
  });
  const PublicationType = IDL.Variant({
    'solo' : IDL.Null,
    'collaboration' : IDL.Null,
    'anthologies' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'authorNote' : IDL.Opt(IDL.Text),
    'publishedAt' : Time,
    'imageUrl' : IDL.Opt(ExternalBlob),
    'category' : BlogCategory,
  });
  const Cause = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(ExternalBlob),
    'externalUrl' : IDL.Text,
    'causeCategory' : CauseCategory,
  });
  const Feature = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Opt(ExternalBlob),
    'externalUrl' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'shopCategory' : ShopCategory,
    'createdAt' : Time,
    'description' : IDL.Text,
    'imageUrl' : ExternalBlob,
    'fulfillmentType' : FulfillmentType,
    'externalUrl' : IDL.Text,
    'price' : IDL.Text,
  });
  const Publication = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'year' : IDL.Text,
    'description' : IDL.Text,
    'coverImage' : IDL.Opt(ExternalBlob),
    'publicationType' : PublicationType,
    'externalUrl' : IDL.Text,
  });
  const VoicePost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Time,
    'parentId' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [
          IDL.Text,
          BlogCategory,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createCause' : IDL.Func(
        [IDL.Text, CauseCategory, IDL.Text, IDL.Opt(ExternalBlob), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createFeature' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          ShopCategory,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
          FulfillmentType,
        ],
        [IDL.Nat],
        [],
      ),
    'createPublication' : IDL.Func(
        [
          IDL.Text,
          PublicationType,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createVoicePost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'deleteCause' : IDL.Func([IDL.Nat], [], []),
    'deleteFeature' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deletePublication' : IDL.Func([IDL.Nat], [], []),
    'deleteVoicePost' : IDL.Func([IDL.Nat], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllCauses' : IDL.Func([], [IDL.Vec(Cause)], ['query']),
    'getAllFeatures' : IDL.Func([], [IDL.Vec(Feature)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
    'getAllVoicePosts' : IDL.Func([], [IDL.Vec(VoicePost)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostsByCategory' : IDL.Func(
        [BlogCategory],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCause' : IDL.Func([IDL.Nat], [IDL.Opt(Cause)], ['query']),
    'getCausesByCategory' : IDL.Func(
        [CauseCategory],
        [IDL.Vec(Cause)],
        ['query'],
      ),
    'getChildVoicePosts' : IDL.Func([IDL.Nat], [IDL.Vec(VoicePost)], ['query']),
    'getFeature' : IDL.Func([IDL.Nat], [IDL.Opt(Feature)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ShopCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getPublication' : IDL.Func([IDL.Nat], [IDL.Opt(Publication)], ['query']),
    'getPublicationsByType' : IDL.Func(
        [PublicationType],
        [IDL.Vec(Publication)],
        ['query'],
      ),
    'getRootVoicePosts' : IDL.Func([], [IDL.Vec(VoicePost)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVoicePost' : IDL.Func([IDL.Nat], [IDL.Opt(VoicePost)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBlogPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          BlogCategory,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateCause' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          CauseCategory,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateFeature' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Text],
        [],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          ShopCategory,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
          FulfillmentType,
        ],
        [],
        [],
      ),
    'updatePublication' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          PublicationType,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateVoicePost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };