/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BlogPost {
    id: bigint;
    title: string;
    body: string;
    authorNote?: string;
    publishedAt: Time;
    imageUrl?: ExternalBlob;
    category: BlogCategory;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Feature {
    id: bigint;
    name: string;
    description: string;
    imageUrl?: ExternalBlob;
    externalUrl: string;
}
export interface VoicePost {
    id: bigint;
    title: string;
    body: string;
    createdAt: Time;
    parentId?: bigint;
}
export interface Publication {
    id: bigint;
    title: string;
    year: string;
    description: string;
    coverImage?: ExternalBlob;
    publicationType: PublicationType;
    externalUrl: string;
}
export interface Cause {
    id: bigint;
    name: string;
    description: string;
    imageUrl?: ExternalBlob;
    externalUrl: string;
    causeCategory: CauseCategory;
}
export interface Product {
    id: bigint;
    title: string;
    shopCategory: ShopCategory;
    createdAt: Time;
    description: string;
    imageUrl: ExternalBlob;
    fulfillmentType: FulfillmentType;
    externalUrl: string;
    price: string;
}
export interface UserProfile {
    name: string;
}
export enum BlogCategory {
    art = "art",
    letters = "letters",
    lyrics = "lyrics",
    poems = "poems",
    prose = "prose",
    quotes = "quotes",
    essays = "essays",
    photographs = "photographs"
}
export enum CauseCategory {
    earth = "earth",
    mental_health = "mental_health",
    humanity = "humanity"
}
export enum FulfillmentType {
    external_pod = "external_pod",
    digital_download = "digital_download"
}
export enum PublicationType {
    solo = "solo",
    collaboration = "collaboration",
    anthologies = "anthologies"
}
export enum ShopCategory {
    art = "art",
    creativity = "creativity",
    words = "words"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBlogPost(title: string, category: BlogCategory, body: string, imageUrl: ExternalBlob | null, authorNote: string | null): Promise<bigint>;
    createCause(name: string, causeCategory: CauseCategory, description: string, imageUrl: ExternalBlob | null, externalUrl: string): Promise<bigint>;
    createFeature(name: string, description: string, imageUrl: ExternalBlob | null, externalUrl: string): Promise<bigint>;
    createProduct(title: string, shopCategory: ShopCategory, description: string, imageUrl: ExternalBlob, price: string, externalUrl: string, fulfillmentType: FulfillmentType): Promise<bigint>;
    createPublication(title: string, publicationType: PublicationType, description: string, coverImage: ExternalBlob | null, externalUrl: string, year: string): Promise<bigint>;
    createVoicePost(title: string, body: string, parentId: bigint | null): Promise<bigint>;
    deleteBlogPost(id: bigint): Promise<void>;
    deleteCause(id: bigint): Promise<void>;
    deleteFeature(id: bigint): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    deletePublication(id: bigint): Promise<void>;
    deleteVoicePost(id: bigint): Promise<void>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllCauses(): Promise<Array<Cause>>;
    getAllFeatures(): Promise<Array<Feature>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllPublications(): Promise<Array<Publication>>;
    getAllVoicePosts(): Promise<Array<VoicePost>>;
    getBlogPost(id: bigint): Promise<BlogPost | null>;
    getBlogPostsByCategory(category: BlogCategory): Promise<Array<BlogPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCause(id: bigint): Promise<Cause | null>;
    getCausesByCategory(category: CauseCategory): Promise<Array<Cause>>;
    getChildVoicePosts(parentId: bigint): Promise<Array<VoicePost>>;
    getFeature(id: bigint): Promise<Feature | null>;
    getProduct(id: bigint): Promise<Product | null>;
    getProductsByCategory(category: ShopCategory): Promise<Array<Product>>;
    getPublication(id: bigint): Promise<Publication | null>;
    getPublicationsByType(publicationType: PublicationType): Promise<Array<Publication>>;
    getRootVoicePosts(): Promise<Array<VoicePost>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVoicePost(id: bigint): Promise<VoicePost | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBlogPost(id: bigint, title: string, category: BlogCategory, body: string, imageUrl: ExternalBlob | null, authorNote: string | null): Promise<void>;
    updateCause(id: bigint, name: string, causeCategory: CauseCategory, description: string, imageUrl: ExternalBlob | null, externalUrl: string): Promise<void>;
    updateFeature(id: bigint, name: string, description: string, imageUrl: ExternalBlob | null, externalUrl: string): Promise<void>;
    updateProduct(id: bigint, title: string, shopCategory: ShopCategory, description: string, imageUrl: ExternalBlob, price: string, externalUrl: string, fulfillmentType: FulfillmentType): Promise<void>;
    updatePublication(id: bigint, title: string, publicationType: PublicationType, description: string, coverImage: ExternalBlob | null, externalUrl: string, year: string): Promise<void>;
    updateVoicePost(id: bigint, title: string, body: string, parentId: bigint | null): Promise<void>;
}
import type { BlogCategory as _BlogCategory, BlogPost as _BlogPost, Cause as _Cause, CauseCategory as _CauseCategory, ExternalBlob as _ExternalBlob, Feature as _Feature, FulfillmentType as _FulfillmentType, Product as _Product, Publication as _Publication, PublicationType as _PublicationType, ShopCategory as _ShopCategory, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, VoicePost as _VoicePost, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBlogPost(arg0: string, arg1: BlogCategory, arg2: string, arg3: ExternalBlob | null, arg4: string | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(arg0, to_candid_BlogCategory_n10(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(arg0, to_candid_BlogCategory_n10(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createCause(arg0: string, arg1: CauseCategory, arg2: string, arg3: ExternalBlob | null, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCause(arg0, to_candid_CauseCategory_n15(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCause(arg0, to_candid_CauseCategory_n15(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async createFeature(arg0: string, arg1: string, arg2: ExternalBlob | null, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createFeature(arg0, arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFeature(arg0, arg1, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createProduct(arg0: string, arg1: ShopCategory, arg2: string, arg3: ExternalBlob, arg4: string, arg5: string, arg6: FulfillmentType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, to_candid_ShopCategory_n17(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_FulfillmentType_n19(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, to_candid_ShopCategory_n17(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg3), arg4, arg5, to_candid_FulfillmentType_n19(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async createPublication(arg0: string, arg1: PublicationType, arg2: string, arg3: ExternalBlob | null, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPublication(arg0, to_candid_PublicationType_n21(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPublication(arg0, to_candid_PublicationType_n21(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async createVoicePost(arg0: string, arg1: string, arg2: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVoicePost(arg0, arg1, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVoicePost(arg0, arg1, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteCause(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCause(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCause(arg0);
            return result;
        }
    }
    async deleteFeature(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeature(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeature(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deletePublication(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePublication(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePublication(arg0);
            return result;
        }
    }
    async deleteVoicePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVoicePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVoicePost(arg0);
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCauses(): Promise<Array<Cause>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCauses();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCauses();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeatures(): Promise<Array<Feature>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeatures();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeatures();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublications(): Promise<Array<Publication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublications();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublications();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllVoicePosts(): Promise<Array<VoicePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVoicePosts();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVoicePosts();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: bigint): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostsByCategory(arg0: BlogCategory): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostsByCategory(to_candid_BlogCategory_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostsByCategory(to_candid_BlogCategory_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCause(arg0: bigint): Promise<Cause | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCause(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCause(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCausesByCategory(arg0: CauseCategory): Promise<Array<Cause>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCausesByCategory(to_candid_CauseCategory_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCausesByCategory(to_candid_CauseCategory_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChildVoicePosts(arg0: bigint): Promise<Array<VoicePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildVoicePosts(arg0);
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildVoicePosts(arg0);
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeature(arg0: bigint): Promise<Feature | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeature(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeature(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: ShopCategory): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_ShopCategory_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_ShopCategory_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublication(arg0: bigint): Promise<Publication | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublication(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublication(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicationsByType(arg0: PublicationType): Promise<Array<Publication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicationsByType(to_candid_PublicationType_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicationsByType(to_candid_PublicationType_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRootVoicePosts(): Promise<Array<VoicePost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRootVoicePosts();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRootVoicePosts();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoicePost(arg0: bigint): Promise<VoicePost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoicePost(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoicePost(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: bigint, arg1: string, arg2: BlogCategory, arg3: string, arg4: ExternalBlob | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1, to_candid_BlogCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1, to_candid_BlogCategory_n10(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n14(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateCause(arg0: bigint, arg1: string, arg2: CauseCategory, arg3: string, arg4: ExternalBlob | null, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCause(arg0, arg1, to_candid_CauseCategory_n15(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCause(arg0, arg1, to_candid_CauseCategory_n15(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateFeature(arg0: bigint, arg1: string, arg2: string, arg3: ExternalBlob | null, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeature(arg0, arg1, arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeature(arg0, arg1, arg2, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: ShopCategory, arg3: string, arg4: ExternalBlob, arg5: string, arg6: string, arg7: FulfillmentType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, to_candid_ShopCategory_n17(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_FulfillmentType_n19(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, to_candid_ShopCategory_n17(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_FulfillmentType_n19(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async updatePublication(arg0: bigint, arg1: string, arg2: PublicationType, arg3: string, arg4: ExternalBlob | null, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublication(arg0, arg1, to_candid_PublicationType_n21(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublication(arg0, arg1, to_candid_PublicationType_n21(this._uploadFile, this._downloadFile, arg2), arg3, await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async updateVoicePost(arg0: bigint, arg1: string, arg2: string, arg3: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVoicePost(arg0, arg1, arg2, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVoicePost(arg0, arg1, arg2, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
function from_candid_BlogCategory_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogCategory): BlogCategory {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_BlogPost_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_CauseCategory_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CauseCategory): CauseCategory {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_Cause_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cause): Promise<Cause> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Feature_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Feature): Promise<Feature> {
    return await from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_FulfillmentType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FulfillmentType): FulfillmentType {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_PublicationType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicationType): PublicationType {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_Publication_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Publication): Promise<Publication> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ShopCategory_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShopCategory): ShopCategory {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_VoicePost_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoicePost): VoicePost {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): Promise<BlogPost | null> {
    return value.length === 0 ? null : await from_candid_BlogPost_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cause]): Promise<Cause | null> {
    return value.length === 0 ? null : await from_candid_Cause_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Feature]): Promise<Feature | null> {
    return value.length === 0 ? null : await from_candid_Feature_n38(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n41(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Publication]): Promise<Publication | null> {
    return value.length === 0 ? null : await from_candid_Publication_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VoicePost]): VoicePost | null {
    return value.length === 0 ? null : from_candid_VoicePost_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    body: string;
    authorNote: [] | [string];
    publishedAt: _Time;
    imageUrl: [] | [_ExternalBlob];
    category: _BlogCategory;
}): Promise<{
    id: bigint;
    title: string;
    body: string;
    authorNote?: string;
    publishedAt: Time;
    imageUrl?: ExternalBlob;
    category: BlogCategory;
}> {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        authorNote: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.authorNote)),
        publishedAt: value.publishedAt,
        imageUrl: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.imageUrl)),
        category: from_candid_BlogCategory_n30(_uploadFile, _downloadFile, value.category)
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    imageUrl: [] | [_ExternalBlob];
    externalUrl: string;
    causeCategory: _CauseCategory;
}): Promise<{
    id: bigint;
    name: string;
    description: string;
    imageUrl?: ExternalBlob;
    externalUrl: string;
    causeCategory: CauseCategory;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        imageUrl: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.imageUrl)),
        externalUrl: value.externalUrl,
        causeCategory: from_candid_CauseCategory_n35(_uploadFile, _downloadFile, value.causeCategory)
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    imageUrl: [] | [_ExternalBlob];
    externalUrl: string;
}): Promise<{
    id: bigint;
    name: string;
    description: string;
    imageUrl?: ExternalBlob;
    externalUrl: string;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        imageUrl: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.imageUrl)),
        externalUrl: value.externalUrl
    };
}
async function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    shopCategory: _ShopCategory;
    createdAt: _Time;
    description: string;
    imageUrl: _ExternalBlob;
    fulfillmentType: _FulfillmentType;
    externalUrl: string;
    price: string;
}): Promise<{
    id: bigint;
    title: string;
    shopCategory: ShopCategory;
    createdAt: Time;
    description: string;
    imageUrl: ExternalBlob;
    fulfillmentType: FulfillmentType;
    externalUrl: string;
    price: string;
}> {
    return {
        id: value.id,
        title: value.title,
        shopCategory: from_candid_ShopCategory_n43(_uploadFile, _downloadFile, value.shopCategory),
        createdAt: value.createdAt,
        description: value.description,
        imageUrl: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.imageUrl),
        fulfillmentType: from_candid_FulfillmentType_n45(_uploadFile, _downloadFile, value.fulfillmentType),
        externalUrl: value.externalUrl,
        price: value.price
    };
}
async function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    year: string;
    description: string;
    coverImage: [] | [_ExternalBlob];
    publicationType: _PublicationType;
    externalUrl: string;
}): Promise<{
    id: bigint;
    title: string;
    year: string;
    description: string;
    coverImage?: ExternalBlob;
    publicationType: PublicationType;
    externalUrl: string;
}> {
    return {
        id: value.id,
        title: value.title,
        year: value.year,
        description: value.description,
        coverImage: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.coverImage)),
        publicationType: from_candid_PublicationType_n50(_uploadFile, _downloadFile, value.publicationType),
        externalUrl: value.externalUrl
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    body: string;
    createdAt: _Time;
    parentId: [] | [bigint];
}): {
    id: bigint;
    title: string;
    body: string;
    createdAt: Time;
    parentId?: bigint;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        createdAt: value.createdAt,
        parentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.parentId))
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    art: null;
} | {
    letters: null;
} | {
    lyrics: null;
} | {
    poems: null;
} | {
    prose: null;
} | {
    quotes: null;
} | {
    essays: null;
} | {
    photographs: null;
}): BlogCategory {
    return "art" in value ? BlogCategory.art : "letters" in value ? BlogCategory.letters : "lyrics" in value ? BlogCategory.lyrics : "poems" in value ? BlogCategory.poems : "prose" in value ? BlogCategory.prose : "quotes" in value ? BlogCategory.quotes : "essays" in value ? BlogCategory.essays : "photographs" in value ? BlogCategory.photographs : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    earth: null;
} | {
    mental_health: null;
} | {
    humanity: null;
}): CauseCategory {
    return "earth" in value ? CauseCategory.earth : "mental_health" in value ? CauseCategory.mental_health : "humanity" in value ? CauseCategory.humanity : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    art: null;
} | {
    creativity: null;
} | {
    words: null;
}): ShopCategory {
    return "art" in value ? ShopCategory.art : "creativity" in value ? ShopCategory.creativity : "words" in value ? ShopCategory.words : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    external_pod: null;
} | {
    digital_download: null;
}): FulfillmentType {
    return "external_pod" in value ? FulfillmentType.external_pod : "digital_download" in value ? FulfillmentType.digital_download : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    solo: null;
} | {
    collaboration: null;
} | {
    anthologies: null;
}): PublicationType {
    return "solo" in value ? PublicationType.solo : "collaboration" in value ? PublicationType.collaboration : "anthologies" in value ? PublicationType.anthologies : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cause>): Promise<Array<Cause>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Cause_n33(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Feature>): Promise<Array<Feature>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Feature_n38(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n41(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Publication>): Promise<Array<Publication>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Publication_n48(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VoicePost>): Array<VoicePost> {
    return value.map((x)=>from_candid_VoicePost_n53(_uploadFile, _downloadFile, x));
}
function to_candid_BlogCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogCategory): _BlogCategory {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_CauseCategory_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CauseCategory): _CauseCategory {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FulfillmentType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FulfillmentType): _FulfillmentType {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PublicationType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationType): _PublicationType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_ShopCategory_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShopCategory): _ShopCategory {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogCategory): {
    art: null;
} | {
    letters: null;
} | {
    lyrics: null;
} | {
    poems: null;
} | {
    prose: null;
} | {
    quotes: null;
} | {
    essays: null;
} | {
    photographs: null;
} {
    return value == BlogCategory.art ? {
        art: null
    } : value == BlogCategory.letters ? {
        letters: null
    } : value == BlogCategory.lyrics ? {
        lyrics: null
    } : value == BlogCategory.poems ? {
        poems: null
    } : value == BlogCategory.prose ? {
        prose: null
    } : value == BlogCategory.quotes ? {
        quotes: null
    } : value == BlogCategory.essays ? {
        essays: null
    } : value == BlogCategory.photographs ? {
        photographs: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CauseCategory): {
    earth: null;
} | {
    mental_health: null;
} | {
    humanity: null;
} {
    return value == CauseCategory.earth ? {
        earth: null
    } : value == CauseCategory.mental_health ? {
        mental_health: null
    } : value == CauseCategory.humanity ? {
        humanity: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShopCategory): {
    art: null;
} | {
    creativity: null;
} | {
    words: null;
} {
    return value == ShopCategory.art ? {
        art: null
    } : value == ShopCategory.creativity ? {
        creativity: null
    } : value == ShopCategory.words ? {
        words: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FulfillmentType): {
    external_pod: null;
} | {
    digital_download: null;
} {
    return value == FulfillmentType.external_pod ? {
        external_pod: null
    } : value == FulfillmentType.digital_download ? {
        digital_download: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationType): {
    solo: null;
} | {
    collaboration: null;
} | {
    anthologies: null;
} {
    return value == PublicationType.solo ? {
        solo: null
    } : value == PublicationType.collaboration ? {
        collaboration: null
    } : value == PublicationType.anthologies ? {
        anthologies: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
